spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-status-check
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
            - Method=GET,POST,PUT,DELETE

        - id: account-status-check
          uri: lb://account-service
          predicates:
            - Path=/api/v1/account/**
            - Method=GET,POST,PUT,DELETE


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

server:
  port: 7777